export const ADD_COURSE_TO_FAVOURITE = 'ADD_COURSE_TO_FAVOURITE'
export const DELETE_COURSE_FROM_FAVOURITE = 'DELETE_COURSE_FROM_FAVOURITE'
export const ADD_COURSE_TO_COMPARATIVE = 'ADD_COURSE_TO_COMPARATIVE'
export const DELETE_COURSE_FROM_COMPARATIVE = 'DELETE_COURSE_FROM_COMPARATIVE'